# -- Markup --
# These settings are required for the theme to function.

[goldmark.parser]
  wrapStandAloneImageWithinParagraph = false
[goldmark.parser.attritube]
  block = true
[goldmark.renderer]
  unsafe = true
[goldmark.renderHooks]
[goldmark.renderHooks.image]
  enableDefault = true

[highlight]
  noClasses = true

[tableOfContents]
  startLevel = 2
  endLevel = 4