[[main]]
  name = "Dokumentation"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "Beispiele"
  pageRef = "samples"
  weight = 20

[[main]]
  name = "Genutzt von"
  pageRef = "users"
  weight = 30

[[main]]
  name = "GitHub"
  url = "https://github.com/jpanther/congo"
  weight = 40
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
