# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "fire"
defaultAppearance = "dark" 
autoSwitchAppearance = false

defaultThemeColor = "#FFFFFF"

enableSearch = false
enableCodeCopy = false
enableImageLazyLoading = true
enableImageWebp = true
enableQuicklink = true

# robots = ""
fingerprintAlgorithm = "sha256"

[header]
  layout = "hamburger"
  # logo = "/images/logo.png"
  # logoDark = ""
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = false

[homepage]
  layout = "custom" # valid options: page, profile, custom
  showRecent = true
  recentLimit = 2
  showTaxonomies = true

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editAppendPath = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showComments = true
  # sharingLinks = ["x-twitter","GitHub", "instagram", "email"]

[list]
  showBreadcrumbs = true
  showSummary = false
  showTableOfContents = true
  showTaxonomies = true
  groupByYear = false
  paginationWidth = 1
  disqusShortname = "electrikserpentine-github-io"

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[customCSS]
customCSS = ["css/custom.css"]

[imaging]
  resampleFilter = "box"
  quality = 75
  anchor = "smart"

[privacy]
  [privacy.disqus]
    disable = false