# Standard taxonomies
category = "categories"
tag = "tags"
series = "series"
social = "social"

# Custom taxonomies
technology = "technologies"
serpent = "serpents"
skill = "skills"
project = "projects"

# Content type taxonomies
tutorial = "tutorials"
article = "articles"
showcase = "showcases"

# Meta taxonomies
mood = "moods"
difficulty = "difficulties"