title = 'Electrik⚡️Serpentine'
baseURL = 'https://electrikserpentine.github.io/'
languageCode = 'en-us'
theme = 'ananke'

[menu]
	[[menu.header]]
	 name = "Elektron⚡Ophis"
	 weight = 0
	 url = "blog"
	[[menu.header]]
	 name = "The Serpent"
	 weight = 1
	 url = "about"
	[[menu.header]]
	 name = "Ophis⚡"
	 weight = 2
	 url = "contact" 

readingTime = true # Show reading time on post page
published = true # show published data on post page
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3

[sitemap]
	changefreq = "monthly"
	priority = 0.5
	filename = "sitemap.xml"

[params]
	text_color = ""
	favicon = "/favicon.ico"
	site_logo = ""
	description = "Fucking Around & Finding Out; "
	background_color_class = "bg-near-black"
	recent_posts_number = 2

[[params.social]]
key = 0
name = "github"
url = "https://github.com/electrikyouthh"
target = "_blank"
aria = "Github Profile"

[[params.social]]
key = 1
name = "instagram"
url = "https://instagram.com/electrikyouthx"
aria = "Instagram"

[params.author]
	name = " Mila" # Website & RSS feed author
	email = "scribblelyts@gmail.com" # RSS feed email address
	  