## -- Site Configuration --

baseURL = 'https://electrikserpentine.github.io/'
title = 'Electrik⚡️Serpentine'
languageCode = 'en-us'

theme = "congo"
defaultContentLanguage = "en"
contentDir= "content"

[module]
[[module.imports]]
  path = "github.com/jpanther/congo/v2"

enableRobotsTXT = true 
summaryLength = 0
enableEmoji = true

[pagination]
  pagerSize = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
  page = ["HTML"]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[services.googleAnalytics]
  ID = "G-J9839Z36YT"

[services]
  [services.disqus]
   shortname = 'electrikserpentine-github-io'
